package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"

	"github.com/dprio/clean-arch-orders/internal/infrastructure/graph"
	"github.com/dprio/clean-arch-orders/internal/infrastructure/graph/model"
	"github.com/dprio/clean-arch-orders/internal/usecase/createorder"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input *model.OrderRequest) (*model.OrderResponse, error) {
	in := createorder.Input{
		Price: input.Price,
		Tax:   input.Tax,
	}

	out, err := r.createOrderUseCase.Execute(ctx, in)
	if err != nil {
		return nil, err
	}

	return &model.OrderResponse{
		ID:         out.ID,
		Price:      out.Price,
		Tax:        out.Tax,
		FinalPrice: out.FinalPrice,
	}, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
